<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create new currency' => 'Добавить новую валюту',
    'Currency disabled.' => 'Валюта отключена',
    'Currency disabling failed.' => 'Ошибка при отключении валюты',
    'Currency enabled.' => 'Валюта включена',
    'Currency enabling failed.' => 'Ошибка при включении валюты',
    'Currency set as default failed.' => 'Ошибка при установке валюты по умолчанию',
    'Currency set as default.' => 'Валюта установвлена по умолчанию',
    'Reset filter' => 'Сбросить фильтр',
    'disabled' => 'отключена',
    'Active' => 'Активная',
    'Are you sure you want to disable this currency?' => 'Вы уверены что хотите отключить эту валюту?',
    'Are you sure you want to enable this currency?' => 'Вы уверены что хотите включить эту валюту?',
    'Are you sure you want to set this currency as default?' => 'Вы уверены что хотите сделать эту валюту валютой по умолчанию?',
    'Code' => 'Код',
    'Currencies' => 'Валюты',
    'Currency code' => 'Код валюты',
    'Currency creation failed.' => 'Произошла ошибка при создании валюты',
    'Currency delete failed.' => 'Произошла ошибка при удалении валюты',
    'Currency name' => 'Название валюты',
    'Currency rate' => 'Курс валюты',
    'Currency symbol' => 'Символ валюты',
    'Currency update failed.' => 'Произошла ошибка при обновлении валюты',
    'Currency was created.' => 'Валюта создана',
    'Currency was deleted.' => 'Валюта обновлена',
    'Default' => 'Стандартая',
    'Disable' => 'Выключить',
    'Enable' => 'Включить',
    'Name' => 'Название',
    'New currency' => 'Новая валюта',
    'Rate' => 'Курс',
    'Save' => 'Сохранить',
    'Set default' => 'Сделать по умолчанию',
    'Symbol' => 'Символ',
];
